In [3]:
import pandas as pd
import numpy as np


patients=pd.read_csv("../data/raw/patients.csv")
visits=pd.read_csv("../data/raw/visits.csv")
treatments=pd.read_csv("../data/raw/treatments.csv")

print("patients shape:",patients.shape)
print("visits shape:",visits.shape)
print("treatments shape:",treatments.shape)

patients shape: (100, 3)
visits shape: (401, 7)
treatments shape: (100, 2)

In [4]:
patients.head()

   patient_id   age gender
0        1001  63.0   male
1        1002  53.0   male
2        1003  39.0   Male
3        1004  67.0   male
4        1005  32.0      M

In [7]:
treatments.head()

   patient_id    treatment
0        1001  Treatment A
1        1002  Treatment B
2        1003  Treatment B
3        1004  Treatment B
4        1005  Treatment A

In [8]:
visits.head()

   patient_id  visit_number  visit_date  weight    bmi  glucose  systolic_bp
0        1001             1  2025-01-01   73.38  25.39   135.35       112.75
1        1001             2  2025-04-01   71.85  24.86   135.46       117.97
2        1001             3  2025-07-01   76.17  26.36   148.10       150.88
3        1001             4  2025-10-01   71.64  24.79   121.54       122.60
4        1002             1  2025-01-01   82.64  28.60   137.47       130.14

In [9]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   patient_id  100 non-null    int64
 1   age         99 non-null     float64
 2   gender      99 non-null     str
dtypes: float64(1), int64(1), str(1)
memory usage: 2.5 KB

In [10]:
patients.isnull().sum()

patient_id    0
age           1
gender        1
dtype: int64

In [11]:
patients["gender"].value_counts()

gender
Male      26
male      21
F         20
M         17
Female    15
Name: count, dtype: int64

In [13]:
patients["gender"]=patients["gender"].replace({
    "male":"Male",
    "M":"Male",
    "m":"Male",
    "F":"Female"
})
patients.loc[patients["age"]>100,"age"]=np.nan
print(patients["gender"].value_counts())
print(patients.isnull().sum())

gender
Male      64
Female    35
Name: count, dtype: int64
patient_id    0
age           2
gender        1
dtype: int64

In [14]:
patients["age"] = patients["age"].fillna(patients["age"].median())

patients["gender"] = patients["gender"].fillna(patients["gender"].mode()[0])

print(patients.isnull().sum())

patient_id    0
age           0
gender        0
dtype: int64